In [48]:
import pickle
import cv2
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [64]:
X

array([[[[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [1.        ],
         [1.        ],
         [1.        ]],

        [[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [1.        ],
         [1.        ],
         [1.        ]],

        [[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [1.        ],
         [1.        ],
         [1.        ]],

        ...,

        [[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [1.        ],
         [1.        ],
         [1.        ]],

        [[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [1.        ],
         [1.        ],
         [1.        ]],

        [[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [1.        ],
         [1.        ],
         [1.        ]]],


       [[[0.85882353],
         [0.45490196],
         [0.47

In [50]:
y

array([1, 1, 1, ..., 1, 0, 0])

In [65]:
X=X/255
X

array([[[[0.00392157],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]],

        [[0.00392157],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]],

        [[0.00392157],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]],

        ...,

        [[0.00392157],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]],

        [[0.00392157],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]],

        [[0.00392157],
         [0.00392157],
         [0.00392157],
         ...,
         [0.00392157],
         [0.00392157],
         [0.00392157]]],


       [[[0.00336794],
         [0.00178393],
         [0.00

In [52]:
X = X.reshape(-1, 60, 60, 1)
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

In [53]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [54]:
model.fit(X, y, epochs=5, validation_split=0.1)

Epoch 1/5
113/113 [==============================] - 18s 150ms/step - loss: 0.6869 - accuracy: 0.5538 - val_loss: 0.6639 - val_accuracy: 0.6425
Epoch 2/5
113/113 [==============================] - 18s 156ms/step - loss: 0.6364 - accuracy: 0.6439 - val_loss: 0.6261 - val_accuracy: 0.6825
Epoch 3/5
113/113 [==============================] - 17s 148ms/step - loss: 0.5977 - accuracy: 0.6853 - val_loss: 0.5982 - val_accuracy: 0.6900
Epoch 4/5
113/113 [==============================] - 17s 147ms/step - loss: 0.5296 - accuracy: 0.7317 - val_loss: 0.5850 - val_accuracy: 0.7200
Epoch 5/5
113/113 [==============================] - 17s 153ms/step - loss: 0.4666 - accuracy: 0.7793 - val_loss: 0.5743 - val_accuracy: 0.7075


In [55]:
import numpy as np
import tensorflow
CATEGORIES = ['Cat', 'Dog']
def image(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    new_arr = cv2.resize(img, (60, 60))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 60, 60, 1)
    return new_arr

# <!-- model = tensorflow.keras.models.load_model('3x3x64-catvsdog.model') -->

In [56]:
# model = tensorflow.keras.models.load_model('3x3x64-catvsdog.model')

In [67]:
prediction = model.predict([image(r"C:\Users\sowmy\OneDrive\Pictures\Screenshots\0001.jpg")])
print(CATEGORIES[prediction.argmax()])

1/1 [==============================] - 0s 16ms/step
Dog
